<header>


    <a name="UP"></a>
    <div class="m-header2 w3-theme-d1">
        <div class="w3-row">
            <div class="w3-quarter w3-container">
                <img class="m-logo" src="../media/img/logo.png" alt="Logo de Creaciones Julieth" title="Creaciones Julieth">
            </div>
            <div class="w3-threequarter w3-container">
                <div class="tit1">Creaciones Juliet</div>
                <span class="tit2">Panel de <i>Instalación</i></span>
            </div>
        </div>
    </div>

    <a name="UP"></a>
    <a href="#UP"><button class="m-boton-go-up">&uparrow;</button></a>
</header>