<a name="UP"></a>
<header>
    <div class="w3-white is-Size01">
        <div class="container-fluid">
            <div class="col-md-3">
                <div class="container-fluid w3-center" style="padding-top: 3%">
                    <a href="inicio.php"><img class="is-logo" src="../media/img/LogoCreaciones.png" alt="Logo de Creaciones Julieth" title="Creaciones Julieth"></a>
                </div>
            </div>
            <div class="col-md-8">
                <div class="container-fluid">
                    <div class="is-Tamaño-Letra01">Creaciones Julieth</div>
                    <br>
                    <h3 class="w3-center is-Tamaño-Letra02 is-TipodeLetra-01 w3-hide-medium w3-hide-small">Uniformes Escolares - Diario y Deportivo - Dotaciones - Programación Bordados - Screen</h3>
                </div>
            </div>
        </div>
    </div>
    <br>
    <a href="#UP"><button class="is-Button-up">&uparrow;</button></a>
    <div id="CARRITO"></div>
</header>