    <a name="UP"></a>
    <div class="m-header2 w3-black">
        <div class="container-fluid">
            <div class="col-md-3">
                <div class="container-fluid w3-center" style="padding-top: 3%">
                    <a href="admin_panel.php"><img class="is-logo" src="../media/img/LogoCreacionesAdmin0.png" alt="Logo de Creaciones Julieth" title="Creaciones Julieth"></a>
                </div>
            </div>
            <div class="col-md-8">
                <div class="container-fluid">
                    <div class="is-Title-Header-Admin-01">Creaciones Julieth</div>
                    <span class="is-Title-Header-Admin-02">Panel de <i>Administrador</i></span>
                </div>
            </div>
        </div>
        <br>
    </div>
    <a name="UP"></a>
    <a href="#UP"><button class="m-boton-go-up">&uparrow;</button></a>
    <body style="background-color: #000;">

    <nav class="m-nav">
        <ul class="w3-navbar w3-theme-dark w3-hide-medium w3-hide-small w3-small">
            <li><a href="gestion_productos.php" class="w3-padding-4 w3-hover-blue">Gestión de Productos</a></li>
            <li><a href="gestion_categorias.php" class="w3-padding-4 w3-hover-light-blue">Gestión de Categorías</a></li>
            <!--<li><a href="#" class="w3-padding-4 w3-hover-gray">Gestión de Catalogos</a></li>-->
            <li><a href="gestion_inventarios.php" class="w3-padding-4 w3-hover-amber">Gestión de Inventarios</a></li>
            <li><a href="gestion_usuarios_crud.php" class="w3-padding-4 w3-hover-yellow">Gestión de Usuarios</a></li>
            <!--<li><a href="#" class="w3-padding-4 w3-hover-green">Gestión de Pedidos</a></li>-->
            <li><a href="gestion_pedidos_facturas.php" class="w3-padding-4 w3-hover-green">Gestión de Pedidos-Facturas</a></li>
            <li><a href="gestion_reportes.php" class="w3-padding-4 w3-hover-black">Gestión de Reportes</a></li>
            <li><a href="inicio.php" class="w3-padding-4 w3-hover-aqua">Pagina de Inicio</a></li>
        </ul>
    </nav>

</header>